#!/bin/bash
#Assume you have docker setup correctly

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
VM_NAME=dev
IMG_TAG=hikki/devstack
CONTAINER_NAME=dev

$DIR/setup_vm
eval $(docker-machine env "$VM_NAME")

docker exec -it $VM_NAME bash
