#!/bin/bash
#Assume you have docker setup correctly

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
IMG_TAG=hikki/devstack

$DIR/setup_vm
eval $(docker-machine env "$VM_NAME")

echo "Build Image..."
docker build -t "$IMG_TAG" "$DIR"
echo "Build Image... Success!"

echo "Pushing Image..."
docker login
docker push "$IMG_TAG"
echo "Pushing Image... Success!"
