#!/bin/bash
#Assume you have docker setup correctly

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
VM_NAME=dev
IMG_TAG=hikki/devstack

$DIR/setup_vm
eval $(docker-machine env "$VM_NAME")

echo "Pushing Image..."
docker login
docker push "$IMG_TAG"
echo "Pushing Image... Success!"
