#!/bin/bash
#Assume you have docker setup correctly

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
VM_NAME=dev
IMG_TAG=hikki/devstack
CONTAINER_NAME=dev

$DIR/setup_vm
eval $(docker-machine env "$VM_NAME")

echo "Stop Container..."
docker stop "$CONTAINER_NAME"
echo "Stop Container... Success!"


echo "Create Container..."
docker rm $CONTAINER_NAME;
docker create --name="$CONTAINER_NAME" -itp 3000:3000 "$IMG_TAG"
echo "Create Container... Success!"

echo "Start Container..."
docker start "$CONTAINER_NAME"
echo "Start Container... Success!"
