#!/bin/bash
#Assume you have docker setup correctly

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
IMG_TAG=hikki/devstack
CONTAINER_NAME=dev-ubuntu

$DIR/setup_vm
eval $(docker-machine env "$VM_NAME")

echo "Create Container..."
docker rm -f $CONTAINER_NAME;
docker create --name="$CONTAINER_NAME" "$IMG_TAG"
echo "Create Container... Success!"

echo "Start Container..."
docker start -a "$CONTAINER_NAME"
echo "Start Container... Success!"
