#!/bin/bash
#Assume you have docker setup correctly

VM_IP=192.168.77.1/24
VM_NAME=dev

echo "Setup Docker VM..."
docker-machine create -d virtualbox --virtualbox-hostonly-cidr "$VM_IP" "$VM_NAME"
docker-machine start "$VM_NAME"
echo "Setup Docker VM... Success!"
